dataSources:
- name: dbt_nthu_kktv
  type: duckdb
  dbt:
    profile: dbt_nthu_kktv
    target: dev
    projectDir: .

profiler:
#   table:
#     # the maximum row count to profile. (Default unlimited)
#     limit: 1000000
#     duplicateRows: false

# The tables to include/exclude
# includes: []
# excludes: []

# tables:
#   my-table-name:
#     # description of the table
#     description: "this is a table description"
#     columns:
#       my-col-name:
#         # description of the column
#         description: "this is a column description"

telemetry:
  id: 53b4ece21a3342168ad26f5a0634b199
